project("zetanet")
    language("C++")
    kind("SharedLib")
    files({
        "*.cc",
        "*.h"
    })
    defines("COMPILE_DLL")
    includedirs({
        ".",
        "../",
        "../vendor/equilibrium",
        "../vendor/fmtlib/include",
        "../vendor/lz4/lib",
    })
    links({
        "base",
        "fmtlib",
        "lz4",
    })
    